# IaS 

parameters: # defaults for any parameters that aren't specified
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  vmImage: ubuntu-latest

jobs:
- job: Build
  pool:
    vmImage: ${{parameters.vmImage}}
  steps:
  - task: Maven@3
    displayName: 'Build Maven Packages'
    inputs:
      mavenPomFile: 'Application/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: CopyFiles@2
    displayName: 'Copy Build Artifacts'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*.war
        **/*jar-with-dependencies.jar
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy ARM Template'
    inputs:
      SourceFolder: 'ArmTemplates'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'